name: Build, Test, Run

on:
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Post23@me
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # - name: Validate Gradle Wrapper
      #   uses: gradle/wrapper-validation-action@v1
      #   with:
      #     gradle-version: '8.4'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Check gradle version
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Set up Database and Verify Table
        run: |
          psql -h localhost -U postgres -d postgres -c "CREATE TABLE IF NOT EXISTS wildlife_tracker (Address CHARACTER VARYING (500), Species TEXT, Quantity INTEGER, Ecosystem CHARACTER VARYING);"
          psql -h localhost -U postgres -d postgres -c "\dt"
        env:
          PGPASSWORD: Post23@me

      - name: Setup Database
        run: ./gradlew flywayMigrate

      - name: Run with Gradle
        run: ./gradlew run

