name: Build, Test, Run

on:
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: Post23@me
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Connect to PostgreSQL
        run: node client.js

      # - name: Validate Gradle Wrapper
      #   uses: gradle/wrapper-validation-action@v1
      #   with:
      #     gradle-version: '8.4'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

#      - name: Wait for PostgreSQL to be ready
#        run: |
#          until pg_isready -h localhost -p 5432 -U postgres; do
#            echo "Waiting for PostgreSQL..."
#            sleep 2
#          done

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Check gradle version
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run with Gradle
        run: ./gradlew run

